"""
MIRAGE Configuration Module

Centralized configuration constants and settings.

Usage:
    from core.config import (
        ENTITY_SIMILARITY_THRESHOLD,
        MAX_CONTEXT_TOKENS,
        RETRIEVAL_TOP_K_DEFAULT,
    )
"""

from .constants import (
    # Entity extraction & resolution
    ENTITY_SIMILARITY_THRESHOLD,
    ENTITY_CONFIDENCE_BOOST_MULTI,
    ENTITY_CONFIDENCE_BOOST_DUAL,
    ENTITY_FREQUENCY_BOOST,
    ENTITY_FREQUENCY_THRESHOLD,
    ENTITY_MAX_CONFIDENCE,
    ENTITY_WEIGHT_LLM,
    ENTITY_WEIGHT_CAMEL,
    ENTITY_WEIGHT_SPACY,
    ENTITY_WEIGHT_PATTERN,
    # Relationship extraction
    COOCCURRENCE_WINDOW,
    MIN_RELATIONSHIP_CONFIDENCE,
    MAX_RELATIONSHIPS_PER_PAIR,
    # Community detection
    LOUVAIN_RESOLUTION,
    MIN_COMMUNITY_SIZE,
    MAX_COMMUNITY_LEVELS,
    DEFAULT_COMMUNITY_LEVEL,
    # Community summarization
    MAX_ENTITIES_IN_SUMMARY,
    MAX_RELATIONSHIPS_IN_SUMMARY,
    MAX_SUMMARY_TOKENS,
    SUMMARIZATION_TEMPERATURE,
    # Retrieval configuration
    RETRIEVAL_TOP_K_DEFAULT,
    RETRIEVAL_TOP_K_MAX,
    RETRIEVAL_MIN_SCORE,
    VALIDATION_RELEVANCE_THRESHOLD,
    VALIDATION_MIN_RELEVANT_RATIO,
    VALIDATION_MAX_CORRECTIONS,
    # Fusion & ranking
    RRF_K,
    MODE_WEIGHT_NAIVE,
    MODE_WEIGHT_LOCAL,
    MODE_WEIGHT_GLOBAL,
    MODE_WEIGHT_HYBRID,
    MODE_WEIGHT_SEMANTIC,
    # REFRAG compression
    REFRAG_CHUNK_SIZE_TOKENS,
    REFRAG_COMPRESSION_RATIO_BASE,
    REFRAG_IMPORTANCE_THRESHOLD,
    REFRAG_AGGRESSIVE_RATIO,
    # Context limits
    MAX_CONTEXT_TOKENS,
    MAX_RESPONSE_TOKENS,
    MAX_ENTITIES_IN_CONTEXT,
    MAX_RELATIONSHIPS_IN_CONTEXT,
    MAX_COMMUNITIES_TO_SEARCH,
    GLOBAL_SEARCH_MIN_RELEVANCE,
    # Chunking configuration
    CHUNK_SIZE_DEFAULT,
    CHUNK_OVERLAP_DEFAULT,
    SEMANTIC_CHUNK_THRESHOLD,
    SEMANTIC_CHUNK_MIN,
    SEMANTIC_CHUNK_MAX,
    # Embedding configuration
    EMBEDDING_DIM,
    EMBEDDING_MODEL,
    EMBEDDING_BATCH_SIZE,
    # LLM configuration
    TGI_ENDPOINT_DEFAULT,
    LLM_MAX_TOKENS_DEFAULT,
    LLM_TEMPERATURE_DEFAULT,
    LLM_TEMPERATURE_FACTUAL,
    LLM_REQUEST_TIMEOUT,
    # Evaluation metrics targets
    TARGET_TTFT_MS,
    TARGET_E2E_LATENCY_MS,
    TARGET_THROUGHPUT_QPS,
    TARGET_MRR,
    TARGET_NDCG_AT_10,
    TARGET_PRECISION_AT_5,
    TARGET_RECALL_AT_10,
    TARGET_ANSWER_RELEVANCY,
    TARGET_FAITHFULNESS,
    TARGET_CONTEXT_RELEVANCY,
    TARGET_ENTITY_F1,
    TARGET_LINKING_ACCURACY,
    # Cache configuration
    CACHE_TTL_DEFAULT,
    CACHE_MAX_SIZE,
    # Logging & monitoring
    METRICS_WINDOW_SIZE,
    LOG_LEVEL_DEBUG,
    LOG_LEVEL_PRODUCTION,
)

__all__ = [
    # Entity extraction & resolution
    "ENTITY_SIMILARITY_THRESHOLD",
    "ENTITY_CONFIDENCE_BOOST_MULTI",
    "ENTITY_CONFIDENCE_BOOST_DUAL",
    "ENTITY_FREQUENCY_BOOST",
    "ENTITY_FREQUENCY_THRESHOLD",
    "ENTITY_MAX_CONFIDENCE",
    "ENTITY_WEIGHT_LLM",
    "ENTITY_WEIGHT_CAMEL",
    "ENTITY_WEIGHT_SPACY",
    "ENTITY_WEIGHT_PATTERN",
    # Relationship extraction
    "COOCCURRENCE_WINDOW",
    "MIN_RELATIONSHIP_CONFIDENCE",
    "MAX_RELATIONSHIPS_PER_PAIR",
    # Community detection
    "LOUVAIN_RESOLUTION",
    "MIN_COMMUNITY_SIZE",
    "MAX_COMMUNITY_LEVELS",
    "DEFAULT_COMMUNITY_LEVEL",
    # Community summarization
    "MAX_ENTITIES_IN_SUMMARY",
    "MAX_RELATIONSHIPS_IN_SUMMARY",
    "MAX_SUMMARY_TOKENS",
    "SUMMARIZATION_TEMPERATURE",
    # Retrieval configuration
    "RETRIEVAL_TOP_K_DEFAULT",
    "RETRIEVAL_TOP_K_MAX",
    "RETRIEVAL_MIN_SCORE",
    "VALIDATION_RELEVANCE_THRESHOLD",
    "VALIDATION_MIN_RELEVANT_RATIO",
    "VALIDATION_MAX_CORRECTIONS",
    # Fusion & ranking
    "RRF_K",
    "MODE_WEIGHT_NAIVE",
    "MODE_WEIGHT_LOCAL",
    "MODE_WEIGHT_GLOBAL",
    "MODE_WEIGHT_HYBRID",
    "MODE_WEIGHT_SEMANTIC",
    # REFRAG compression
    "REFRAG_CHUNK_SIZE_TOKENS",
    "REFRAG_COMPRESSION_RATIO_BASE",
    "REFRAG_IMPORTANCE_THRESHOLD",
    "REFRAG_AGGRESSIVE_RATIO",
    # Context limits
    "MAX_CONTEXT_TOKENS",
    "MAX_RESPONSE_TOKENS",
    "MAX_ENTITIES_IN_CONTEXT",
    "MAX_RELATIONSHIPS_IN_CONTEXT",
    "MAX_COMMUNITIES_TO_SEARCH",
    "GLOBAL_SEARCH_MIN_RELEVANCE",
    # Chunking configuration
    "CHUNK_SIZE_DEFAULT",
    "CHUNK_OVERLAP_DEFAULT",
    "SEMANTIC_CHUNK_THRESHOLD",
    "SEMANTIC_CHUNK_MIN",
    "SEMANTIC_CHUNK_MAX",
    # Embedding configuration
    "EMBEDDING_DIM",
    "EMBEDDING_MODEL",
    "EMBEDDING_BATCH_SIZE",
    # LLM configuration
    "TGI_ENDPOINT_DEFAULT",
    "LLM_MAX_TOKENS_DEFAULT",
    "LLM_TEMPERATURE_DEFAULT",
    "LLM_TEMPERATURE_FACTUAL",
    "LLM_REQUEST_TIMEOUT",
    # Evaluation metrics targets
    "TARGET_TTFT_MS",
    "TARGET_E2E_LATENCY_MS",
    "TARGET_THROUGHPUT_QPS",
    "TARGET_MRR",
    "TARGET_NDCG_AT_10",
    "TARGET_PRECISION_AT_5",
    "TARGET_RECALL_AT_10",
    "TARGET_ANSWER_RELEVANCY",
    "TARGET_FAITHFULNESS",
    "TARGET_CONTEXT_RELEVANCY",
    "TARGET_ENTITY_F1",
    "TARGET_LINKING_ACCURACY",
    # Cache configuration
    "CACHE_TTL_DEFAULT",
    "CACHE_MAX_SIZE",
    # Logging & monitoring
    "METRICS_WINDOW_SIZE",
    "LOG_LEVEL_DEBUG",
    "LOG_LEVEL_PRODUCTION",
]
